### ISSUE TITLE
Basic fixes [Suggestion]

### ISSUE THREAD

**Issue by RaymondWise** [dmparker0/VBTable#1]
I've run the [RubberDuck](http://rubberduckvba.com/) code inspections tool on this module and exported the list to a file. Most of this can be fixed by the actual add-in Rubberduck. Your call.
[rubberTable.txt](https://github.com/dmparker0/VBTable/files/1905155/rubberTable.txt)

**Comment by dmparker0** [comment]
Thanks for the heads up!

A lot of the issues are Rubberduck bugs. IE it gets confused by "createSheets", which returns either a worksheet object (in which case it uses the Set statement) or an array of worksheets (in which case it doesn't). 

Another big portion of them are just stylistic recommendations that I disagree with. IE it doesn't like it when I use ReDim during initial array declarations. It also wants me to make the functions all explicitly public, which IMO is unnecessary in this case since these functions are all designed to be used by other modules.

The remainder (20-30) should be cleaned up, so I'm closing this for now.

**Comment by RaymondWise** [comment]
For sure on the first point https://github.com/rubberduck-vba/Rubberduck/issues/3752
